/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var m=Object.defineProperty;var u=Object.getOwnPropertyDescriptor;var v=Object.getOwnPropertyNames;var f=Object.prototype.hasOwnProperty;var y=(t,r)=>{for(var o in r)m(t,o,{get:r[o],enumerable:!0})},E=(t,r,o,s)=>{if(r&&typeof r=="object"||typeof r=="function")for(let i of v(r))!f.call(t,i)&&i!==o&&m(t,i,{get:()=>r[i],enumerable:!(s=u(r,i))||s.enumerable});return t};var w=t=>E(m({},"__esModule",{value:!0}),t);var z={};y(z,{default:()=>p});module.exports=w(z);var h=require("obsidian"),S="https://api.openbd.jp/v1/get";function k(t){return t.trim().replace(/-/g,"")}var $=`
.openbd-card { margin: 1em 0; }
.openbd-card-inner {
	display: flex;
	gap: 1.25em;
	align-items: flex-start;
	padding: 1.25em;
	border: none;
	border-radius: 12px;
	background: var(--background-secondary);
	box-shadow: 0 2px 8px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04);
	transition: box-shadow 0.2s ease, transform 0.2s ease;
	position: relative;
	overflow: hidden;
}
.openbd-card-inner::before {
	content: "";
	position: absolute;
	left: 0;
	top: 0;
	bottom: 0;
	width: 3px;
	background: linear-gradient(180deg, var(--interactive-accent), var(--interactive-accent-hover));
	border-radius: 12px 0 0 12px;
}
.openbd-card-inner:hover {
	box-shadow: 0 8px 24px rgba(0,0,0,0.08), 0 2px 6px rgba(0,0,0,0.04);
}
.openbd-cover {
	flex-shrink: 0;
	line-height: 0;
	margin-left: 4px;
}
.openbd-cover img {
	display: block;
	max-height: 160px;
	width: auto;
	border-radius: 8px;
	box-shadow: 0 4px 12px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.06);
	transition: transform 0.2s ease, box-shadow 0.2s ease;
}
.openbd-card-inner:hover .openbd-cover img {
	transform: translateY(-2px);
	box-shadow: 0 8px 20px rgba(0,0,0,0.14), 0 4px 8px rgba(0,0,0,0.06);
}
.openbd-meta {
	flex: 1;
	min-width: 0;
	font-size: 0.925em;
	letter-spacing: 0.01em;
}
.openbd-title {
	font-weight: 700;
	font-size: 1.05em;
	margin-bottom: 0.5em;
	line-height: 1.35;
	letter-spacing: -0.01em;
	color: var(--text-normal);
}
.openbd-author {
	color: var(--text-muted);
	font-size: 0.9em;
	margin-top: 0.25em;
	font-weight: 500;
}
.openbd-publisher, .openbd-pubdate {
	color: var(--text-faint);
	font-size: 0.85em;
	margin-top: 0.15em;
}
.openbd-loading, .openbd-error {
	color: var(--text-muted);
	margin: 0.5em 0;
	font-size: 0.9em;
}
.openbd-error { color: var(--text-error); }
`,p=class extends h.Plugin{constructor(){super(...arguments);this.styleEl=null}addStyle(){this.styleEl=document.createElement("style"),this.styleEl.textContent=$,document.head.appendChild(this.styleEl)}async onload(){this.addStyle(),this.registerMarkdownCodeBlockProcessor("isbn",async(o,s,i)=>{let g=k(o);if(!g){s.createEl("p",{text:"ISBN\u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002",cls:"openbd-error"});return}let a=s.createEl("div",{cls:"openbd-card"});a.createEl("p",{text:"\u53D6\u5F97\u4E2D\u2026",cls:"openbd-loading"});try{let l=await(await fetch(`${S}?isbn=${encodeURIComponent(g)}`)).json();if(a.empty(),!Array.isArray(l)||l.length===0||!l[0]){a.createEl("p",{text:"\u66F8\u8A8C\u60C5\u5831\u304C\u898B\u3064\u304B\u308A\u307E\u305B\u3093\u3067\u3057\u305F\u3002",cls:"openbd-error"});return}let e=l[0].summary;if(!e){a.createEl("p",{text:"\u66F8\u8A8C\u60C5\u5831\u304C\u3042\u308A\u307E\u305B\u3093\u3002",cls:"openbd-error"});return}let x=a.createEl("div",{cls:"openbd-card-inner"});if(e.cover){let n=x.createEl("div",{cls:"openbd-cover"}),b=n.createEl("img",{attr:{src:e.cover,alt:e.title}});b.onerror=()=>n.remove()}let c=x.createEl("div",{cls:"openbd-meta"});if(e.title&&c.createEl("div",{cls:"openbd-title",text:e.title}),e.author&&c.createEl("div",{cls:"openbd-author",text:`\u8457: ${e.author}`}),e.publisher&&c.createEl("div",{cls:"openbd-publisher",text:e.publisher}),e.pubdate){let n=e.pubdate,b=n.length>=8?`${n.slice(0,4)}/${n.slice(4,6)}/${n.slice(6,8)}`:n;c.createEl("div",{cls:"openbd-pubdate",text:b})}}catch(d){a.empty(),a.createEl("p",{text:`\u53D6\u5F97\u306B\u5931\u6557\u3057\u307E\u3057\u305F: ${d instanceof Error?d.message:String(d)}`,cls:"openbd-error"})}})}onunload(){var o;(o=this.styleEl)==null||o.remove(),this.styleEl=null}};
